// The July-17 guard. A Tauri command is reachable in a packaged build only if
// it is registered in THREE places in lockstep: main.rs `generate_handler!`,
// build.rs's `AppManifest::commands(&[...])` (which generates
// permissions/autogenerated/<name>.toml), and an allow entry in some
// capabilities/*.json. Dev builds mask omissions because stale autogenerated
// tomls survive on disk — that's how the co-presence commands died in the
// packaged app (fixed 07-17, a6668a1) and how speak/stop_speaking ran for weeks
// unregistered (fixed 07-21, 3c96b7e). This test parses all three sources and
// fails on any drift, before packaging can hide it.
//
// It deliberately reads source text rather than linking the crate: the whole
// point is to check the three files against each other, not runtime behavior.

use std::collections::BTreeSet;

const BUILD_RS: &str = include_str!("../build.rs");
const MAIN_RS: &str = include_str!("../src/main.rs");

// Every other string in a split-on-quote is inside quotes. Good enough for the
// two blocks we aim it at; the tripwire tests below fail loudly if the source
// ever reshapes in a way this misparses.
fn quoted(block: &str) -> BTreeSet<String> {
    block
        .split('"')
        .skip(1)
        .step_by(2)
        .map(str::to_string)
        .collect()
}

fn build_rs_commands() -> BTreeSet<String> {
    let start = BUILD_RS
        .find("commands(&[")
        .expect("build.rs no longer contains a commands(&[...]) block");
    let block = &BUILD_RS[start..];
    let end = block
        .find("])")
        .expect("build.rs commands block has no terminator");
    quoted(&block[..end])
}

fn handler_commands() -> BTreeSet<String> {
    let start = MAIN_RS
        .find("generate_handler![")
        .expect("main.rs no longer contains generate_handler![...]");
    let block = &MAIN_RS[start + "generate_handler![".len()..];
    let end = block
        .find(']')
        .expect("generate_handler! block has no terminator");
    block[..end]
        .split([',', '\n'])
        .map(str::trim)
        .filter(|t| !t.is_empty())
        .map(|t| t.rsplit("::").next().unwrap().trim().to_string())
        .collect()
}

fn capability_allows() -> BTreeSet<String> {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/capabilities");
    let mut out = BTreeSet::new();
    for entry in std::fs::read_dir(dir).expect("capabilities/ directory") {
        let path = entry.expect("capabilities dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let raw = std::fs::read_to_string(&path).expect("read capability file");
        let json: serde_json::Value = serde_json::from_str(&raw)
            .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", path.display()));
        for perm in json["permissions"].as_array().into_iter().flatten() {
            if let Some(name) = perm.as_str().and_then(|p| p.strip_prefix("allow-")) {
                out.insert(name.replace('-', "_"));
            }
        }
    }
    out
}

// Tripwires: if a parser silently under-extracts (source reformatted, block
// renamed), these fail before the subset assertions can vacuously pass.
#[test]
fn parsers_extract_plausible_command_sets() {
    assert!(
        build_rs_commands().len() >= 30,
        "build.rs parser extracted only {} commands — parser rot?",
        build_rs_commands().len()
    );
    assert!(
        handler_commands().len() >= 30,
        "generate_handler! parser extracted only {} commands — parser rot?",
        handler_commands().len()
    );
    assert!(
        capability_allows().len() >= 30,
        "capability parser extracted only {} allows — parser rot?",
        capability_allows().len()
    );
}

#[test]
fn every_handler_command_is_registered_in_build_rs() {
    let missing: Vec<_> = handler_commands()
        .difference(&build_rs_commands())
        .cloned()
        .collect();
    assert!(
        missing.is_empty(),
        "commands in generate_handler! but missing from build.rs commands(&[...]) — \
         they will die with 'not allowed by ACL' in a clean packaged build: {missing:?}"
    );
}

#[test]
fn every_registered_command_is_allowed_by_a_capability() {
    let missing: Vec<_> = build_rs_commands()
        .difference(&capability_allows())
        .cloned()
        .collect();
    assert!(
        missing.is_empty(),
        "commands registered in build.rs but allowed by no capabilities/*.json — \
         no webview can invoke them: {missing:?}"
    );
}

// The pure modules are the tested core of the shell; the moment one grows a
// tauri dependency it stops being constructible in a unit test and the
// functional-core/imperative-shell split starts rotting. Enforce it textually.
#[test]
fn pure_modules_have_no_tauri_imports() {
    for (name, text) in [
        ("js.rs", include_str!("../src/browser/js.rs")),
        ("labels.rs", include_str!("../src/browser/labels.rs")),
        ("geometry.rs", include_str!("../src/browser/geometry.rs")),
    ] {
        assert!(
            !text.contains("use tauri") && !text.contains("tauri::"),
            "browser/{name} is a PURE module — it must not touch tauri"
        );
    }
}

#[test]
fn no_capability_allows_an_unregistered_command() {
    let orphans: Vec<_> = capability_allows()
        .difference(&build_rs_commands())
        .cloned()
        .collect();
    assert!(
        orphans.is_empty(),
        "capability allow entries with no matching build.rs command — \
         stale grants that mask real drift: {orphans:?}"
    );
}
