defmodule BusterClaw.Introduction do
  @moduledoc """
  Generates `INTRODUCTION.md` — an orientation document for the AI model: what
  Buster Claw is, the workspace layout, working conventions (daily activity
  summaries), and the full CLI command surface.

  The document is installed into the workspace root (regenerated on launch and
  whenever the workspace changes) and is also injected into the chat model's
  system context so the model is given the command list directly.
  """

  alias BusterClaw.Commands
  alias BusterClaw.Library.Artifact

  @filename "INTRODUCTION.md"

  @doc "The introduction file name."
  def filename, do: @filename

  @doc "Absolute path of the installed introduction in the current workspace."
  def path, do: Path.join(Artifact.workspace_root(), @filename)

  @doc "Write the freshly generated introduction to the workspace root."
  def install! do
    File.mkdir_p!(Artifact.workspace_root())
    File.write!(path(), markdown())
    {:ok, path()}
  end

  @doc "Best-effort install; never raises (used at boot)."
  def ensure do
    install!()
  rescue
    _ -> :error
  catch
    _, _ -> :error
  end

  @doc "The installed file's content, falling back to a freshly generated copy."
  def read do
    case File.read(path()) do
      {:ok, content} -> content
      {:error, _reason} -> markdown()
    end
  end

  @doc "The full introduction markdown (prose + conventions + command surface)."
  def markdown do
    """
    <!-- Generated by Buster Claw. This file orients the AI model and is
    regenerated on launch — treat it as read-only reference. -->

    # Buster Claw — Operating Guide

    You are the AI model driving **Buster Claw**, a desktop runtime for
    agentically managing the user's web interactivity. Through one auditable
    command surface you browse and fetch the web, act on Google Workspace
    (Gmail, Calendar), pull from integrations (GitHub, Sentry, Umami), connect
    MCP servers, and deliver results to Slack/Discord/Telegram/email. Content you
    gather can be captured into a **Library** and analyzed into reports. Every
    command, outbound send, and untrusted fetch is recorded on the Security
    (Sentinel) audit feed.

    ## Workspace layout

    Everything you create lives under the workspace folder (`#{Artifact.workspace_root()}`):

    - `library/` — the document store. Raw documents under `library/raw/<date>/`,
      generated reports under `library/reports/<date>/`.
    - `sources/` — saved source material.
    - `analysis/` — analysis outputs.
    - `memory/` — durable notes/context.

    ## Daily activity summaries (minutes)

    Keep a running record of everything that happens in Buster Claw, like meeting
    minutes. Each day, create a folder **inside the library** named
    `MM-DD-YY-summary` (the current date — e.g. `#{example_date()}-summary`) and
    write that day's summary/minutes there: every ingest, analysis, delivery,
    command run, and notable decision. Append throughout the day; one dated folder
    per day so the history is easy to scan.

    ## Command surface (CLI)

    These are the commands you can run (via the `buster-claw` CLI / API / agent
    tools). **Safe** commands you may run directly; **restricted** commands change
    state or send data and require the user's confirmation before they execute.

    #{command_surface_markdown()}
    """
  end

  @doc "Markdown list of the command catalog grouped by trust tier."
  def command_surface_markdown do
    commands = Commands.list_commands()
    {safe, restricted} = Enum.split_with(commands, &(tier(&1) == :safe))

    [
      "### Safe (agent-callable)",
      render_commands(safe),
      "",
      "### Restricted (require confirmation)",
      render_commands(restricted)
    ]
    |> Enum.join("\n")
  end

  defp render_commands([]), do: "_None._"

  defp render_commands(commands) do
    commands
    |> Enum.sort_by(&Map.fetch!(&1, :name))
    |> Enum.map_join("\n", fn cmd ->
      "- `#{Map.fetch!(cmd, :name)}` — #{Map.get(cmd, :description, "")}"
    end)
  end

  defp tier(cmd), do: Map.get(cmd, :tier, :safe)

  defp example_date, do: "05-30-26"
end
