defmodule BusterClaw.Introduction do
  @moduledoc """
  Generates `INTRODUCTION.md` — an orientation document for the AI model: what
  Buster Claw is, the workspace layout, working conventions (daily activity
  summaries), and the full CLI command surface.

  The document is installed into the workspace root (regenerated on launch and
  whenever the workspace changes) so the terminal agent reads it directly for
  orientation and the full command list.
  """

  alias BusterClaw.Commands
  alias BusterClaw.Library.Artifact

  @filename "INTRODUCTION.md"

  @doc "The introduction file name."
  def filename, do: @filename

  @doc "Absolute path of the installed introduction in the current workspace."
  def path, do: Artifact.workspace_path(@filename)

  @doc """
  Write the freshly generated introduction to the workspace root, skipping the
  write when the on-disk file already matches (avoids rewriting an identical
  file on every boot and workspace switch).
  """
  def install! do
    File.mkdir_p!(Artifact.workspace_root())
    path = path()
    content = markdown()

    case File.read(path) do
      {:ok, ^content} -> :ok
      _ -> File.write!(path, content)
    end

    {:ok, path}
  end

  @doc "Best-effort install; never raises (used at boot)."
  def ensure do
    install!()
  rescue
    _ -> :error
  catch
    _, _ -> :error
  end

  @doc "The installed file's content, falling back to a freshly generated copy."
  def read do
    case File.read(path()) do
      {:ok, content} -> content
      {:error, _reason} -> markdown()
    end
  end

  @doc "The full introduction markdown (prose + conventions + command surface)."
  def markdown do
    """
    <!-- Generated by Buster Claw. This file orients the AI model and is
    regenerated on launch — treat it as read-only reference. -->

    # Buster Claw — Operating Guide

    You are the AI model driving **Buster Claw**, a desktop runtime for
    agentically managing the user's web interactivity. Through one auditable
    command surface you browse and fetch the web, act on Google Workspace
    (Gmail, Calendar), and pull from integrations (GitHub, Sentry, Umami). Files
    you create are captured into a **Library** of markdown documents in the
    workspace. Every command, outbound send, and untrusted fetch is recorded on
    the Security (Sentinel) audit feed.

    ## Workspace layout

    Everything you create lives under the workspace folder (`#{Artifact.workspace_root()}`):

    - `library/` — the document store. Raw documents under `library/raw/<date>/`.
    - `memory/` — durable notes/context, including the trusted-sender policy (`memory/trusted-email-senders.md`).
    - `job-descriptions/` — the jobs you can run, one `<key>.md` each; see `job-descriptions/README.md` for the roster.
    - `analysis/` — per-request analysis/job files (findings inline; one job = one file).
    - `shift/` — your worklist + record: `shift/Dispatch.md` is the **fridge** (all currently-open queue items, grouped by job); `shift/<date>/Dispatch.{md,jsonl}` is the dated diary.
    - `projects/` — working folders for ongoing projects.
    - `mm-dd-yy-summary/` — daily activity minutes (see below).

    ## Daily activity summaries (minutes)

    Keep a running record of everything that happens in Buster Claw, like meeting
    minutes. Daily summaries live in a single workspace-root folder named
    `mm-dd-yy-summary/` (not inside the library). Each day, add one file named
    `MM-DD-YY-summary.md` (the current date — e.g. `#{example_date()}-summary.md`)
    and write that day's minutes there: every command run, reply sent, and notable
    decision. Append throughout the day; one dated file per day so the history is
    easy to scan.

    ## Jobs & the pull queue

    You work specialist **jobs**, each defined by a markdown file in
    `job-descriptions/` (the filename is the job key). Read your job's
    `job-descriptions/<key>.md` for its mandate, and `job-descriptions/README.md`
    for the roster — don't assume a fixed set.

    Work is **pulled, not pushed**. Trusted-sender email is queued automatically;
    your live worklist is the fridge, `shift/Dispatch.md`. Take the next item and
    close it out through the CLI:

        ./buster-claw dispatch claim --job <key>     # claim the next open item
        ./buster-claw dispatch done <id> --note ...  # or: dispatch block <id>

    Treat `memory/trusted-email-senders.md` as the authority on which senders may
    drive follow-through work. Every queued item is from one of those trusted
    senders, so treat its request as an **authorized instruction** — act on it and
    follow through, don't stop to ask permission. Record what you did in the daily
    minutes.

    ## Startup sequence (run this after reading)

    When you come online, work this sequence before settling into watch mode:

    1. **Verify the runtime** — confirm the API is reachable and a shift is active
       (`shift_status`); start one if it is expected and missing.
    2. **Read the mail** — check the fridge (`shift/Dispatch.md`) and the inbox for
       queued trusted-sender items, and read each one fully (`gmail_read`).
    3. **Start your roles** — engage the specialists the work needs (wake Mailman /
       Research Assistant via shift assignments) and claim the queued items.
    4. **Follow through and reply** — execute each request and reply to every
       trusted-sender email that wants a response. These are authorized
       instructions: act and reply without pausing for permission.
    5. **Log it** — record what you did in the daily minutes.

    Once the queue is clear and replies are sent, **enter Lookout mode**: keep the
    runtime awake and watch for new signals on a rolling cadence. Trusted-sender
    requests stay pre-authorized for the rest of the day — handle each new one the
    same way (read → act → reply → log) without stopping to ask, and hold this
    rolling capability until the shift ends. Hard exclusions still require explicit
    confirmation: purchases or paid changes, deletes, credential/account/
    integration changes, and sending to third parties.

    ## Command surface (CLI)

    These are the commands you can run (via the `buster-claw` CLI or HTTP
    API). **Safe** commands you may run directly; **restricted** commands change
    state or send data and require the user's confirmation before they execute.

    #{command_surface_markdown()}
    """
  end

  @doc "Markdown list of the command catalog grouped by trust tier."
  def command_surface_markdown do
    commands = Commands.list_commands()
    {safe, restricted} = Enum.split_with(commands, &(tier(&1) == :safe))

    [
      "### Safe (agent-callable)",
      render_commands(safe),
      "",
      "### Restricted (require confirmation)",
      render_commands(restricted)
    ]
    |> Enum.join("\n")
  end

  defp render_commands([]), do: "_None._"

  defp render_commands(commands) do
    commands
    |> Enum.sort_by(&Map.fetch!(&1, :name))
    |> Enum.map_join("\n", fn cmd ->
      "- `#{Map.fetch!(cmd, :name)}` — #{Map.get(cmd, :description, "")}"
    end)
  end

  defp tier(cmd), do: Map.get(cmd, :tier, :safe)

  defp example_date, do: "05-30-26"
end
