defmodule BusterClaw.WorkspaceCLI do
  @moduledoc """
  Installs the DataZone-local `./buster-claw` launcher used by terminal commands.

  The launcher preserves the terminal's working directory in the workspace while
  delegating command execution to either the dev escript or the bundled release
  binary in packaged installs.
  """

  alias BusterClaw.Library.Artifact

  @launcher_name "buster-claw"
  @marker "# BUSTER_CLAW_GENERATED_CLI_LAUNCHER=1"
  # The packaged release has no escript, so the launcher evals this string to
  # hand argv to the CLI. It MUST be valid Elixir on a single line: the
  # multi-clause `case` uses `;` between clauses, because a multi-line form
  # collapsed to spaces (as the old launcher did) is a syntax error.
  @release_eval ~s/case System.argv() do ["--" | args] -> BusterClaw.CLI.main(args); args -> BusterClaw.CLI.main(args) end/

  @doc "Ensure the current workspace has an executable `./buster-claw` launcher."
  def ensure do
    path = launcher_path()

    with :ok <- File.mkdir_p(Path.dirname(path)),
         {:ok, target} <- target(),
         :ok <- write_launcher(path, launcher_script(target)) do
      {:ok, path}
    end
  end

  @doc "Absolute path to the generated launcher in the current workspace."
  def launcher_path do
    Artifact.workspace_path(@launcher_name)
  end

  defp write_launcher(path, content) do
    case File.read(path) do
      {:ok, ^content} ->
        File.chmod(path, 0o755)

      {:ok, existing} ->
        if String.contains?(existing, @marker) do
          write_executable(path, content)
        else
          {:error, :launcher_exists}
        end

      {:error, :enoent} ->
        write_executable(path, content)

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp write_executable(path, content) do
    with :ok <- File.write(path, content) do
      File.chmod(path, 0o755)
    end
  end

  defp target do
    cond do
      path = env_cli_path() ->
        {:ok, {:exec, path}}

      path = release_binary_path() ->
        {:ok, {:release, path}}

      path = dev_escript_path() ->
        {:ok, {:exec, path}}

      true ->
        {:error, :cli_not_found}
    end
  end

  defp env_cli_path do
    [System.get_env("BUSTER_CLAW_CLI_PATH"), System.get_env("BUSTER_CLAW_CLI")]
    |> Enum.find_value(&present/1)
    |> case do
      nil -> nil
      path -> Path.expand(path)
    end
  end

  defp release_binary_path do
    with root when is_binary(root) <- present(System.get_env("RELEASE_ROOT")) do
      name = present(System.get_env("RELEASE_NAME")) || "buster_claw"
      path = Path.join([root, "bin", name]) |> Path.expand()
      if File.exists?(path), do: path
    end
  end

  defp dev_escript_path do
    path = Path.expand(@launcher_name, File.cwd!())

    cond do
      path == Path.expand(launcher_path()) -> nil
      File.exists?(path) -> path
      true -> nil
    end
  end

  defp launcher_script({:exec, path}) do
    """
    #!/bin/sh
    #{@marker}
    # Generated by Buster Claw. Run commands from the DataZone while delegating
    # to the app CLI.
    BC_CLI=#{shell_quote(path)}
    #{missing_target_guard()}
    exec "$BC_CLI" "$@"
    """
  end

  defp launcher_script({:release, path}) do
    """
    #!/bin/sh
    #{@marker}
    # Generated by Buster Claw. Run commands from the DataZone while delegating
    # to the bundled app release.
    BC_CLI=#{shell_quote(path)}
    #{missing_target_guard()}
    export BUSTER_CLAW_CLI_EVAL=1
    exec "$BC_CLI" eval #{shell_quote(@release_eval)} -- "$@"
    """
  end

  # The launcher names an ABSOLUTE path chosen when the app last started. That
  # path can rot underneath it — the app gets uninstalled, moved, or (the case
  # that cost an evening on 07-30) replaced while the server that would rewrite
  # this file keeps running, so nothing regenerates it. Without this guard the
  # failure surfaces as a bare `/bin/sh` line:
  #
  #     ./buster-claw: line 6: /Applications/…/buster_claw: No such file or directory
  #
  # which names a path but explains nothing and suggests no fix. `on-duty` is the
  # front door to the autonomous loop, so a mute failure there is expensive.
  # Exit 127 is the conventional "command not found".
  defp missing_target_guard do
    """
    if [ ! -x "$BC_CLI" ]; then
      echo "buster-claw: the Buster Claw CLI this launcher points at is missing:" >&2
      echo "  $BC_CLI" >&2
      echo "" >&2
      echo "This launcher was generated the last time Buster Claw started. The" >&2
      echo "binary it named has since been moved, deleted, or uninstalled." >&2
      echo "" >&2
      echo "Fix: start Buster Claw once to regenerate this launcher, or reinstall" >&2
      echo "the app. In a dev checkout, \\`mix escript.build\\` then restart the server." >&2
      exit 127
    fi\
    """
  end

  defp present(value) when is_binary(value) do
    value
    |> String.trim()
    |> case do
      "" -> nil
      value -> value
    end
  end

  defp present(_value), do: nil

  defp shell_quote(value) do
    "'#{String.replace(value, "'", "'\"'\"'")}'"
  end
end
