defmodule BusterClaw.WorkspaceCLI do
  @moduledoc """
  Installs the DataZone-local `./buster-claw` launcher used by terminal commands.

  The launcher preserves the terminal's working directory in the workspace while
  delegating command execution to either the dev escript or the bundled release
  binary in packaged installs.
  """

  alias BusterClaw.Library.Artifact

  @launcher_name "buster-claw"
  @marker "# BUSTER_CLAW_GENERATED_CLI_LAUNCHER=1"
  @release_eval """
  case System.argv() do
    ["--" | args] -> BusterClaw.CLI.main(args)
    args -> BusterClaw.CLI.main(args)
  end
  """

  @doc "Ensure the current workspace has an executable `./buster-claw` launcher."
  def ensure do
    path = launcher_path()

    with :ok <- File.mkdir_p(Path.dirname(path)),
         {:ok, target} <- target(),
         :ok <- write_launcher(path, launcher_script(target)) do
      {:ok, path}
    end
  end

  @doc "Absolute path to the generated launcher in the current workspace."
  def launcher_path do
    Path.join(Artifact.workspace_root(), @launcher_name)
  end

  defp write_launcher(path, content) do
    case File.read(path) do
      {:ok, ^content} ->
        File.chmod(path, 0o755)

      {:ok, existing} ->
        if String.contains?(existing, @marker) do
          write_executable(path, content)
        else
          {:error, :launcher_exists}
        end

      {:error, :enoent} ->
        write_executable(path, content)

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp write_executable(path, content) do
    with :ok <- File.write(path, content) do
      File.chmod(path, 0o755)
    end
  end

  defp target do
    cond do
      path = env_cli_path() ->
        {:ok, {:exec, path}}

      path = release_binary_path() ->
        {:ok, {:release, path}}

      path = dev_escript_path() ->
        {:ok, {:exec, path}}

      true ->
        {:error, :cli_not_found}
    end
  end

  defp env_cli_path do
    [System.get_env("BUSTER_CLAW_CLI_PATH"), System.get_env("BUSTER_CLAW_CLI")]
    |> Enum.find_value(&present/1)
    |> case do
      nil -> nil
      path -> Path.expand(path)
    end
  end

  defp release_binary_path do
    with root when is_binary(root) <- present(System.get_env("RELEASE_ROOT")) do
      name = present(System.get_env("RELEASE_NAME")) || "buster_claw"
      path = Path.join([root, "bin", name]) |> Path.expand()
      if File.exists?(path), do: path
    end
  end

  defp dev_escript_path do
    path = Path.expand(@launcher_name, File.cwd!())

    cond do
      path == Path.expand(launcher_path()) -> nil
      File.exists?(path) -> path
      true -> nil
    end
  end

  defp launcher_script({:exec, path}) do
    """
    #!/bin/sh
    #{@marker}
    # Generated by Buster Claw. Run commands from the DataZone while delegating
    # to the app CLI.
    exec #{shell_quote(path)} "$@"
    """
  end

  defp launcher_script({:release, path}) do
    eval = @release_eval |> String.replace("\n", " ") |> String.trim()

    """
    #!/bin/sh
    #{@marker}
    # Generated by Buster Claw. Run commands from the DataZone while delegating
    # to the bundled app release.
    export BUSTER_CLAW_CLI_EVAL=1
    exec #{shell_quote(path)} eval #{shell_quote(eval)} -- "$@"
    """
  end

  defp present(value) when is_binary(value) do
    value
    |> String.trim()
    |> case do
      "" -> nil
      value -> value
    end
  end

  defp present(_value), do: nil

  defp shell_quote(value) do
    "'#{String.replace(value, "'", "'\"'\"'")}'"
  end
end
