defmodule BusterClaw.AnalyzerTest do
  # async: false — points :workspace_root at a tmp skills/ dir (approve writes there).
  use BusterClaw.DataCase, async: false

  alias BusterClaw.{Analyzer, Commands, Skills}
  alias BusterClaw.Sentinel.Event
  alias BusterClaw.Skills.Suggestions

  setup do
    root = Path.join(System.tmp_dir!(), "bc_analyzer_#{System.unique_integer([:positive])}")
    File.mkdir_p!(Path.join(root, "library"))

    prev_ws = Application.get_env(:buster_claw, :workspace_root)
    prev_lib = Application.get_env(:buster_claw, :library_root)
    Application.put_env(:buster_claw, :workspace_root, root)
    Application.put_env(:buster_claw, :library_root, Path.join(root, "library"))

    on_exit(fn ->
      Application.put_env(:buster_claw, :workspace_root, prev_ws)
      Application.put_env(:buster_claw, :library_root, prev_lib)
      File.rm_rf(root)
    end)

    {:ok, root: root}
  end

  # Seed `times` distinct sessions of `commands`, each session an hour apart (well
  # past the 180s session gap) so each is its own clean sequence — mirroring the
  # same multi-step workflow recurring across runs. Explicit timestamps via
  # insert_all (autogenerated `inserted_at` would collapse everything into one
  # session). `offset` lets a test add fresh, later sessions.
  defp seed_sequence(commands, times, offset \\ 0) do
    rows =
      for s <- 1..times,
          {command, i} <- Enum.with_index(commands) do
        at = DateTime.add(~U[2026-06-21 00:00:00Z], (offset + s) * 3600 + i, :second)

        %{
          category: "command_invoke",
          severity: "info",
          message: "#{command} (ok)",
          caller: "trusted",
          metadata: %{"command" => command},
          inserted_at: at
        }
      end

    Repo.insert_all(Event, rows)
  end

  # --- detection ---------------------------------------------------------

  test "scan files a suggestion for a sequence repeated >= the threshold" do
    seed_sequence(["document_list", "dispatch_list"], 3)

    assert %{filed: filed} = Analyzer.scan(analyzer_min_occurrences: 3)
    assert Enum.any?(filed, &(&1.signature == "document_list>dispatch_list"))

    [suggestion] = Suggestions.list()
    assert suggestion.signature == "document_list>dispatch_list"
    assert suggestion.status == "pending"
    assert suggestion.occurrences >= 3
  end

  test "scan ignores sequences below the threshold" do
    seed_sequence(["document_list", "dispatch_list"], 2)

    assert %{filed: []} = Analyzer.scan(analyzer_min_occurrences: 3)
    assert Suggestions.list() == []
  end

  test "scan ignores a single command repeated (a loop, not a composition)" do
    seed_sequence(["gmail_search"], 6)

    assert %{filed: []} = Analyzer.scan(analyzer_min_occurrences: 2)
  end

  test "re-scanning bumps occurrences on the existing pending suggestion, not a dup" do
    seed_sequence(["document_list", "dispatch_list"], 3)

    Analyzer.scan(analyzer_min_occurrences: 3)
    first = hd(Suggestions.list())

    # A later scan re-observes the same sequence and bumps the existing row.
    Analyzer.scan(analyzer_min_occurrences: 3)

    assert [only] = Suggestions.list()
    assert only.id == first.id
    assert only.occurrences > first.occurrences
  end

  # --- approval loop -----------------------------------------------------

  test "approving a suggestion writes an enabled, dispatchable skill" do
    seed_sequence(["document_list", "dispatch_list"], 3)
    Analyzer.scan(analyzer_min_occurrences: 3)
    suggestion = hd(Suggestions.list())

    assert {:ok, name} = Suggestions.approve(suggestion.id)
    assert name == "auto-document-list-dispatch-list"

    # The enabled skill now resolves and runs end to end (both steps are safe reads
    # that need no args).
    assert {:ok, skill} = Skills.fetch(name)
    assert skill.enabled
    assert Enum.any?(Commands.list_skills(), &(&1.name == name))

    assert {:ok, [%{command: "document_list"}, %{command: "dispatch_list"}]} =
             Commands.call(name, %{}, caller: :trusted)

    assert Suggestions.get(suggestion.id).status == "approved"
  end

  test "rejecting a suggestion leaves no skill and marks it rejected" do
    seed_sequence(["document_list", "dispatch_list"], 3)
    Analyzer.scan(analyzer_min_occurrences: 3)
    suggestion = hd(Suggestions.list())

    assert {:ok, _} = Suggestions.reject(suggestion.id)
    assert Suggestions.get(suggestion.id).status == "rejected"
    assert Suggestions.list() == []
    assert :error = Skills.fetch("auto-document-list-dispatch-list")
  end

  # --- command surface + safety -----------------------------------------

  test "the full loop runs through Commands.call" do
    seed_sequence(["document_list", "dispatch_list"], 3)

    assert {:ok, %{filed: [_ | _]}} =
             Commands.call("skill_analyze", %{"min_occurrences" => 3}, caller: :trusted)

    assert {:ok, [view]} = Commands.call("skill_suggestions", %{}, caller: :mcp)
    assert view.status == "pending"

    assert {:ok, %{approved: name}} =
             Commands.call("skill_suggestion_approve", %{"id" => view.id}, caller: :trusted)

    assert {:ok, _} = Commands.call(name, %{}, caller: :trusted)
  end

  test "approving is gated — an untrusted autonomous caller is refused" do
    seed_sequence(["document_list", "dispatch_list"], 3)
    Analyzer.scan(analyzer_min_occurrences: 3)
    id = hd(Suggestions.list()).id

    assert {:error, :requires_confirmation} =
             Commands.call("skill_suggestion_approve", %{"id" => id}, caller: :agent_untrusted)

    # …and nothing was enabled.
    assert :error = Skills.fetch("auto-document-list-dispatch-list")
  end
end
