import Config

# Configure your database
config :buster_claw, BusterClaw.Repo,
  database: Path.expand("../buster_claw_dev.db", __DIR__),
  pool_size: 5,
  # SQLite is single-writer; WAL (the adapter default) lets readers run alongside
  # the one writer, but two writers still serialize. Wait up to 5s for the write
  # lock (the adapter default is 2s) so brief contention between background writers
  # doesn't surface as "Database busy".
  busy_timeout: 5_000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :buster_claw, BusterClawWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "nTd5WuiJVogoqAr1jT6URIYp4BsYSAvl+Ozdr9lJL5ORy5by1QPCFYWanRJfwLWk",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:buster_claw, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:buster_claw, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :buster_claw, BusterClawWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/buster_claw_web/router\.ex$"E,
      ~r"lib/buster_claw_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :buster_claw, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Stable loopback API token for the command surface (HTTP API, CLI, MCP).
# Persisted across dev restarts so shell aliases and MCP configs keep working.
config :buster_claw, :api_token, "dev-token-loopback-only"

# Scoped MCP token: authenticates as the `:mcp` caller, which is restricted to
# safe-tier commands. Hand this (not the full token) to external MCP agents.
config :buster_claw, :mcp_api_token, "dev-mcp-token-safe-tier-only"

# Agent-untrusted token: authenticates as the `:agent_untrusted` caller, handed
# by the Dispatcher to a headless run working untrusted-origin content (refused
# the gated outbound/irreversible commands).
config :buster_claw, :agent_api_token, "dev-agent-token-untrusted-provenance"

# Bundled Google OAuth client placeholder — makes the one-click "Connect
# Google" surfaces render in dev. Clicking through fails at Google's door
# (invalid_client) until real Desktop-app credentials exist; set
# BUSTER_CLAW_GOOGLE_CLIENT_ID/_SECRET (runtime.exs) to test end-to-end.
config :buster_claw, :google_bundled_client, %{
  client_id: "dev-placeholder.apps.googleusercontent.com",
  client_secret: "dev-placeholder-not-a-real-secret"
}
