import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :buster_claw, BusterClawWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# The packaged desktop app binds Phoenix to 127.0.0.1 over plain HTTP;
# SSL is not used because the Tauri webview connects to loopback only.

# Enforce the Content-Security-Policy header in the shipped app (dev stays
# Report-Only so Phoenix LiveReload's inline script keeps working). This is the
# real RCE backstop: a strict `script-src 'self' 'nonce-…'` blocks injected
# inline scripts, event handlers, and `javascript:` URLs from reaching the Tauri
# shell. Only the main LiveView scope runs through this plug; the /browser and
# /ws raw-HTML scopes have no pipeline, so their inline scripts are unaffected.
config :buster_claw, :csp_mode, :enforce

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
