import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :buster_claw, BusterClawWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# The packaged desktop app binds Phoenix to 127.0.0.1 over plain HTTP;
# SSL is not used because the Tauri webview connects to loopback only.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
