defmodule BusterClawWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :buster_claw

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_buster_claw_key",
    signing_salt: "WqwR8sgO",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :buster_claw,
    gzip: not code_reloading?,
    only: BusterClawWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :buster_claw
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {BusterClawWeb.Endpoint, :cache_raw_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BusterClawWeb.Router

  # Only the webhook endpoint consumes `conn.assigns[:raw_body]` (to verify the
  # provider's HMAC signature over the exact bytes), so only that path pays for a
  # full duplicate of the request body. Every other request reads its body
  # straight through the parser without the extra copy.
  def cache_raw_body(conn, opts) do
    if capture_raw_body?(conn) do
      case Plug.Conn.read_body(conn, opts) do
        {:ok, body, conn} ->
          {:ok, body, update_in(conn.assigns[:raw_body], &((&1 || "") <> body))}

        {:more, body, conn} ->
          {:more, body, update_in(conn.assigns[:raw_body], &((&1 || "") <> body))}

        {:error, reason} ->
          {:error, reason}
      end
    else
      Plug.Conn.read_body(conn, opts)
    end
  end

  defp capture_raw_body?(%Plug.Conn{path_info: ["integrations", _name, "webhook"]}), do: true
  defp capture_raw_body?(_conn), do: false
end
