// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCalendarEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCalendarEvent'](arg1, arg2, arg3);
}

export function AddDeliveryDestination(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddDeliveryDestination'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddHook(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddHook'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddJob(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddJob'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddMemory(arg1) {
  return window['go']['main']['App']['AddMemory'](arg1);
}

export function AddProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSource'](arg1, arg2, arg3, arg4);
}

export function AddWebhook(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddWebhook'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ClearMessages() {
  return window['go']['main']['App']['ClearMessages']();
}

export function DeleteCalendarEvent(arg1) {
  return window['go']['main']['App']['DeleteCalendarEvent'](arg1);
}

export function DeleteDeliveryDestination(arg1) {
  return window['go']['main']['App']['DeleteDeliveryDestination'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteHook(arg1) {
  return window['go']['main']['App']['DeleteHook'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteSource(arg1) {
  return window['go']['main']['App']['DeleteSource'](arg1);
}

export function DeleteWebhook(arg1) {
  return window['go']['main']['App']['DeleteWebhook'](arg1);
}

export function GetAnalysisQueue() {
  return window['go']['main']['App']['GetAnalysisQueue']();
}

export function GetCalendarEvents() {
  return window['go']['main']['App']['GetCalendarEvents']();
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetDeliveryDestinations() {
  return window['go']['main']['App']['GetDeliveryDestinations']();
}

export function GetDocumentContent(arg1) {
  return window['go']['main']['App']['GetDocumentContent'](arg1);
}

export function GetDocuments() {
  return window['go']['main']['App']['GetDocuments']();
}

export function GetHooks() {
  return window['go']['main']['App']['GetHooks']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetMemories() {
  return window['go']['main']['App']['GetMemories']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetPendingFiles() {
  return window['go']['main']['App']['GetPendingFiles']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetReportContent(arg1) {
  return window['go']['main']['App']['GetReportContent'](arg1);
}

export function GetReportManifest() {
  return window['go']['main']['App']['GetReportManifest']();
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function GetWebhooks() {
  return window['go']['main']['App']['GetWebhooks']();
}

export function IngestSource(arg1) {
  return window['go']['main']['App']['IngestSource'](arg1);
}

export function QueueDocument(arg1) {
  return window['go']['main']['App']['QueueDocument'](arg1);
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function RemoveMemory(arg1) {
  return window['go']['main']['App']['RemoveMemory'](arg1);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RunJobNow(arg1) {
  return window['go']['main']['App']['RunJobNow'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetActiveProvider(arg1) {
  return window['go']['main']['App']['SetActiveProvider'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function StartAnalysis() {
  return window['go']['main']['App']['StartAnalysis']();
}

export function StartIngest() {
  return window['go']['main']['App']['StartIngest']();
}

export function TestDeliveryDestination(arg1) {
  return window['go']['main']['App']['TestDeliveryDestination'](arg1);
}

export function TestProvider(arg1) {
  return window['go']['main']['App']['TestProvider'](arg1);
}

export function ToggleWebhook(arg1, arg2) {
  return window['go']['main']['App']['ToggleWebhook'](arg1, arg2);
}

export function UpdateCalendarEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCalendarEvent'](arg1, arg2, arg3, arg4);
}

export function UpdateJob(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateJob'](arg1, arg2, arg3, arg4, arg5, arg6);
}
