// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSource'](arg1, arg2, arg3, arg4);
}

export function ClearMessages() {
  return window['go']['main']['App']['ClearMessages']();
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteSource(arg1) {
  return window['go']['main']['App']['DeleteSource'](arg1);
}

export function GetAnalysisQueue() {
  return window['go']['main']['App']['GetAnalysisQueue']();
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetDocuments() {
  return window['go']['main']['App']['GetDocuments']();
}

export function GetIntentions() {
  return window['go']['main']['App']['GetIntentions']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetOrchestratorStatus() {
  return window['go']['main']['App']['GetOrchestratorStatus']();
}

export function GetPendingCount() {
  return window['go']['main']['App']['GetPendingCount']();
}

export function GetPendingFiles() {
  return window['go']['main']['App']['GetPendingFiles']();
}

export function GetReportContent(arg1) {
  return window['go']['main']['App']['GetReportContent'](arg1);
}

export function GetReportManifest() {
  return window['go']['main']['App']['GetReportManifest']();
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function IngestSource(arg1) {
  return window['go']['main']['App']['IngestSource'](arg1);
}

export function QueueDocument(arg1) {
  return window['go']['main']['App']['QueueDocument'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function StartAnalysis() {
  return window['go']['main']['App']['StartAnalysis']();
}

export function StartFullPipeline() {
  return window['go']['main']['App']['StartFullPipeline']();
}

export function StartIngest() {
  return window['go']['main']['App']['StartIngest']();
}
