// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {library} from '../models';
import {ingest} from '../models';

export function ClearMessages():Promise<void>;

export function GetCurrentModel():Promise<string>;

export function GetIntentions():Promise<string>;

export function GetMessages():Promise<Array<main.ChatMessage>>;

export function GetModels():Promise<Array<string>>;

export function GetOrchestratorStatus():Promise<main.OrchestratorStatus>;

export function GetPendingCount():Promise<number>;

export function GetReportManifest():Promise<Array<library.ReportMeta>>;

export function GetSources():Promise<Array<ingest.Source>>;

export function SendMessage(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function StartAnalysis():Promise<main.AnalysisResult>;

export function StartFullPipeline():Promise<main.FullPipelineResult>;

export function StartIngest():Promise<main.IngestResult>;
