// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {orchestrator} from '../models';
import {delivery} from '../models';
import {main} from '../models';
import {scheduler} from '../models';
import {library} from '../models';
import {ingest} from '../models';
import {webhook} from '../models';

export function AddDeliveryDestination(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function AddJob(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string,arg6:string):Promise<void>;

export function AddMemory(arg1:string):Promise<void>;

export function AddProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddSource(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function AddWebhook(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<void>;

export function ClearMessages():Promise<void>;

export function DeleteDeliveryDestination(arg1:string):Promise<void>;

export function DeleteDocument(arg1:string):Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function DeleteSource(arg1:string):Promise<void>;

export function DeleteWebhook(arg1:string):Promise<void>;

export function GetAnalysisQueue():Promise<Array<orchestrator.QueueEntry>>;

export function GetCurrentModel():Promise<string>;

export function GetDeliveryDestinations():Promise<Array<delivery.Destination>>;

export function GetDocuments():Promise<Array<main.DocumentInfo>>;

export function GetJobs():Promise<Array<scheduler.JobState>>;

export function GetMemories():Promise<Array<main.MemoryEntry>>;

export function GetMessages():Promise<Array<main.ChatMessage>>;

export function GetModels():Promise<Array<string>>;

export function GetPendingFiles():Promise<Array<main.PendingFile>>;

export function GetProviders():Promise<Array<main.ProviderInfo>>;

export function GetReportContent(arg1:string):Promise<string>;

export function GetReportManifest():Promise<Array<library.ReportMeta>>;

export function GetSources():Promise<Array<ingest.Source>>;

export function GetWebhooks():Promise<Array<webhook.Hook>>;

export function IngestSource(arg1:string):Promise<main.IngestResult>;

export function QueueDocument(arg1:string):Promise<void>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function RemoveMemory(arg1:number):Promise<void>;

export function RemoveProvider(arg1:string):Promise<void>;

export function RunJobNow(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetActiveProvider(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function StartAnalysis():Promise<main.AnalysisResult>;

export function StartIngest():Promise<main.IngestResult>;

export function TestDeliveryDestination(arg1:string):Promise<void>;

export function TestProvider(arg1:string):Promise<string>;

export function ToggleWebhook(arg1:string,arg2:boolean):Promise<void>;

export function UpdateJob(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string,arg6:string):Promise<void>;
