// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {orchestrator} from '../models';
import {main} from '../models';
import {library} from '../models';
import {ingest} from '../models';

export function AddSource(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function ClearMessages():Promise<void>;

export function DeleteSource(arg1:string):Promise<void>;

export function GetAnalysisQueue():Promise<Array<orchestrator.QueueEntry>>;

export function GetCurrentModel():Promise<string>;

export function GetDocuments():Promise<Array<main.DocumentInfo>>;

export function GetIntentions():Promise<string>;

export function GetMessages():Promise<Array<main.ChatMessage>>;

export function GetModels():Promise<Array<string>>;

export function GetOrchestratorStatus():Promise<main.OrchestratorStatus>;

export function GetPendingCount():Promise<number>;

export function GetPendingFiles():Promise<Array<main.PendingFile>>;

export function GetReportContent(arg1:string):Promise<string>;

export function GetReportManifest():Promise<Array<library.ReportMeta>>;

export function GetSources():Promise<Array<ingest.Source>>;

export function IngestSource(arg1:string):Promise<main.IngestResult>;

export function QueueDocument(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function StartAnalysis():Promise<main.AnalysisResult>;

export function StartFullPipeline():Promise<main.FullPipelineResult>;

export function StartIngest():Promise<main.IngestResult>;
