defmodule BusterClaw.Notifications.Sound do
  @moduledoc """
  The notification sound library — audio files in `<workspace>/sounds/` that
  play when a notification fires, so an alarm is audible without touching the OS.

  Which file plays is routed per event via a map stored in `Settings`
  (`notify_sound_map`, JSON): keys are notification *sources* (chat, terminal,
  email, voicemail, manual), *kinds* (timer, alarm, reminder), or `"default"`.
  Resolution for a fired notification, first match wins: source → kind →
  default → the legacy fallback (`notify.<ext>`, else the first audio file
  alphabetically). Source outranks kind so "a voicemail's timer" sounds like
  voicemail. No sounds at all → the fired modal still shows, silently.

  Served by `NotifySoundController` at `/notify/sound` (resolved default) and
  `/notify/sound/:name` (a specific library file — the name is validated
  against `list/0`, never joined from raw input). Played by the `NotifySound`
  hook when `NotifyLive` sees a notification fire; auditioned by the
  `SoundPreview` hook in Settings → Notify.
  """

  require Logger

  alias BusterClaw.Library.Artifact
  alias BusterClaw.Settings

  @subdir "sounds"
  @preferred "notify"
  @exts ~w(.mp3 .wav .ogg .m4a .aac)
  @content_types %{
    ".mp3" => "audio/mpeg",
    ".wav" => "audio/wav",
    ".ogg" => "audio/ogg",
    ".m4a" => "audio/mp4",
    ".aac" => "audio/aac"
  }

  @map_key "notify_sound_map"
  @enabled_key "sound_enabled"
  # Stored in the routing map to mean "this key plays nothing, on purpose".
  # Not a filename on either layer, so it can never collide with a real sound.
  @silent "silent"
  # Routing keys the map accepts: sources outrank kinds; "default" is the floor.
  # The second row is SOUND_ROADMAP Part II — group A agent-attention (confirm/
  # order/shift/blocked/web), group B arrivals (sms; email/voicemail predate it),
  # group C (security), group D (boot). Every key except "default" has a bundled
  # synthesized fallback (SoundGen), so bundled-defaults-ON works with an empty
  # workspace library.
  @route_keys ~w(chat terminal email voicemail manual timer alarm reminder default) ++
                ~w(confirm order shift blocked web sms security boot)

  # Human labels for the routing keys, in the order a person should meet them:
  # the catch-all, then the kinds you set alarms with, then where a thing came
  # from, then the agent's own noises. Here rather than in a LiveView because
  # two surfaces now offer routing — Settings → Notify and the Studio's
  # assign-on-render — and a label defined twice is a label that drifts.
  @route_labels [
    {"default", "Default"},
    {"timer", "Timers"},
    {"alarm", "Alarms"},
    {"reminder", "Reminders"},
    {"chat", "Chat"},
    {"terminal", "Terminal"},
    {"email", "Email"},
    {"voicemail", "Voicemail"},
    {"manual", "Manual"},
    {"confirm", "Confirm"},
    {"shift", "Shift end"},
    {"blocked", "Blocked"},
    {"web", "Browser"},
    {"order", "Order"},
    {"sms", "SMS"},
    {"security", "Security"},
    {"boot", "Boot"}
  ]

  @doc "Absolute path to the `sounds/` folder in the active workspace."
  def dir, do: Artifact.workspace_path(@subdir)

  @doc """
  Absolute path to the bundled default set (`priv/static/sounds/`, generated by
  `SoundGen` via `scripts/gen_sounds.exs`). Read-only at runtime.
  """
  def bundled_dir, do: Application.app_dir(:buster_claw, "priv/static/sounds")

  # ---------------------------------------------------------------------------
  # Master switch (SOUND_ROADMAP Phase 0)
  # ---------------------------------------------------------------------------

  @doc """
  The one switch above all routing: `false` means nothing rings — bundled
  defaults, workspace files, notifications, everything. Defaults to `true`
  (bundled defaults ship ON, by operator decision 07-28).
  """
  def enabled? do
    Settings.get(@enabled_key) != "false"
  end

  @doc "Flip the master switch."
  def set_enabled(true), do: delete_enabled()

  def set_enabled(false) do
    case Settings.put(@enabled_key, "false") do
      {:ok, _} -> :ok
      {:error, _} = error -> error
    end
  end

  # ON is the absence of the setting, so a fresh install and a re-enabled one
  # are the same state — there is no third "never touched" behavior to reason
  # about.
  defp delete_enabled do
    Settings.delete(@enabled_key)
    :ok
  end

  @doc "Audio file extensions the library accepts."
  def accepted_extensions, do: @exts

  @doc "Routing keys the sound map accepts."
  def route_keys, do: @route_keys

  @doc """
  Routing keys as `{label, key}` in display order — ready for a `select`'s
  `options`, which is how both routing surfaces present them.
  """
  def route_options, do: Enum.map(@route_labels, fn {key, label} -> {label, key} end)

  @doc "Human label for a routing key, or the key itself if it somehow has none."
  def route_label(key) when is_binary(key) do
    Enum.find_value(@route_labels, key, fn {k, label} -> if k == key, do: label end)
  end

  # ---------------------------------------------------------------------------
  # Library
  # ---------------------------------------------------------------------------

  @doc "Sorted basenames of every audio file in the library."
  def list do
    case File.ls(dir()) do
      {:ok, entries} ->
        entries
        |> Enum.sort()
        |> Enum.filter(fn name ->
          String.downcase(Path.extname(name)) in @exts and
            File.regular?(Path.join(dir(), name))
        end)

      _ ->
        []
    end
  end

  @doc """
  Absolute path for a library sound by basename, or `nil` when the name isn't
  in the library. Membership in `list/0` is the allowlist — a name that isn't a
  real directory entry never resolves, so there is no traversal surface.
  """
  def path_for(name) when is_binary(name) do
    if name in list(), do: Path.join(dir(), name)
  end

  def path_for(_), do: nil

  @doc """
  Sorted basenames of the bundled default set — the sixteen synthesized chimes,
  and nothing else.

  **Digest artifacts are excluded.** `mix phx.digest` writes a content-hashed
  copy of every static asset beside the original (`alarm.wav` →
  `alarm-85cf46bf....wav`), so after a release build this directory holds each
  chime twice. Listing both doubled the routing menu in Settings → Notify and
  filled the Studio's sidebar with what reads as system junk. The hash suffix is
  only ever a build product here — this directory ships with exactly what
  `SoundGen` wrote — so recognizing it is safe, and the alternative (a hardcoded
  list of sixteen names) would silently drop the seventeenth chime.
  """
  def bundled_list do
    case File.ls(bundled_dir()) do
      {:ok, entries} ->
        entries
        |> Enum.sort()
        |> Enum.filter(fn name ->
          String.downcase(Path.extname(name)) in @exts and
            not digest_artifact?(name) and
            File.regular?(Path.join(bundled_dir(), name))
        end)

      _ ->
        []
    end
  end

  # `<stem>-<32 hex>.<ext>`, the shape phx.digest appends. Only applied to the
  # bundled directory, whose entire contents we author.
  defp digest_artifact?(name) do
    name |> Path.rootname() |> String.match?(~r/-[0-9a-f]{32}$/)
  end

  @doc "Absolute path for a bundled default by basename — same allowlist posture as `path_for/1`."
  def bundled_path_for(name) when is_binary(name) do
    if name in bundled_list(), do: Path.join(bundled_dir(), name)
  end

  def bundled_path_for(_), do: nil

  @doc """
  Copy the bundled chimes into `<workspace>/sounds/` so the set is real files on
  disk — editable in the Studio, visible in Finder.

  **Never called at boot.** SOUND_ROADMAP Part III rule 1 forbids *seeding*, and
  the reason still holds: an automatic copy would resurrect files the operator
  deleted, which is how "delete that sound" becomes a bug report. This is the
  operator asking, once, on purpose — a different act from the app deciding.

  **Never overwrites.** A name already present is skipped, because that file is
  either the operator's edit or their replacement, and neither should be
  clobbered by a restore. Returns `%{copied: [...], skipped: [...]}`.

  Note the consequence, which is a feature: once a chime exists in the
  workspace, deleting it there falls back to the bundled copy rather than
  removing the sound. That makes "delete my edit" a restore-to-default.
  """
  def install_bundled do
    File.mkdir_p(dir())

    result =
      Enum.reduce(bundled_list(), %{copied: [], skipped: []}, fn name, acc ->
        target = Path.join(dir(), name)

        cond do
          File.exists?(target) -> %{acc | skipped: [name | acc.skipped]}
          File.cp(bundled_path_for(name), target) == :ok -> %{acc | copied: [name | acc.copied]}
          true -> %{acc | skipped: [name | acc.skipped]}
        end
      end)

    %{copied: Enum.reverse(result.copied), skipped: Enum.reverse(result.skipped)}
  end

  @doc "Bundled chimes not yet present in the workspace folder."
  def missing_from_workspace do
    present = MapSet.new(list())
    Enum.reject(bundled_list(), &MapSet.member?(present, &1))
  end

  @doc """
  Two-layer resolution for serving: the workspace wins, the bundled set is the
  floor. Because both layers resolve by basename, a workspace file named
  `confirm.wav` overrides the bundled `confirm.wav` with no routing entry at
  all — drop-a-file-in-Finder is a complete customization story.
  """
  def resolve_path(name), do: path_for(name) || bundled_path_for(name)

  @doc """
  Copy a file into the sound library under a free name, returning that name.

  The deliberate step that moves audio from working material to a finished
  effect — `sounds/studio/` holds what you are editing, `sounds/` holds what the
  app will play unattended, and this is the door between them.

  **Never overwrites**, because this layer overrides bundled chimes by basename:
  installing something called `alarm.wav` would silently replace the built-in
  alarm for good. A taken name gets a `-2`, and the caller is told the name it
  actually got.
  """
  def install_file(src_path, suggested_name)
      when is_binary(src_path) and is_binary(suggested_name) do
    ext = suggested_name |> Path.extname() |> String.downcase()

    cond do
      not File.regular?(src_path) -> {:error, :not_found}
      ext not in @exts -> {:error, :unsupported_format}
      true -> copy_in(src_path, BusterClaw.AudioName.safe_name(suggested_name))
    end
  end

  defp copy_in(src_path, name) do
    File.mkdir_p!(dir())
    free = available_name(name)

    case File.cp(src_path, Path.join(dir(), free)) do
      :ok -> {:ok, free}
      {:error, reason} -> {:error, reason}
    end
  end

  defp available_name(name) do
    if name in list(), do: next_free(Path.rootname(name), Path.extname(name), 2), else: name
  end

  defp next_free(stem, ext, n) do
    candidate = "#{stem}-#{n}#{ext}"
    if candidate in list(), do: next_free(stem, ext, n + 1), else: candidate
  end

  @doc """
  Rename a workspace sound, carrying its routing with it.

  `stem` is the new name without extension; the original extension is kept, so
  a rename cannot change what kind of file this is. Only the workspace layer is
  renameable — `path_for/1` returns nil for a bundled-only chime, which is the
  refusal.

  Two consequences worth knowing, both of them the point rather than side
  effects. Any event routed to the old name is **repointed** (the mirror of
  `delete/1`'s prune — a rename should not silently unhook a notification). And
  because this layer overrides the bundled set **by basename**, renaming
  `confirm.wav` to `doorbell.wav` stops it overriding `confirm` and makes it a
  standalone sound: the built-in comes back. That is what renaming an override
  *means*.
  """
  def rename(name, stem) when is_binary(name) and is_binary(stem) do
    with path when is_binary(path) <- path_for(name),
         {:ok, new_name} <- renamed(name, stem),
         :ok <- refuse_taken(new_name),
         :ok <- File.rename(path, Path.join(dir(), new_name)) do
      repoint_map_value(name, new_name)
      {:ok, new_name}
    else
      nil -> {:error, :not_found}
      {:error, _reason} = error -> error
    end
  end

  def rename(_name, _stem), do: {:error, :not_found}

  # A stem sanitized by Music's sanitizer (shared across every renameable
  # surface), with the ORIGINAL extension reattached — so a rename can never
  # change what kind of file this is, and typing "x.txt" over a .wav yields
  # "x.wav".
  #
  # The emptiness check is on the REQUEST, not the sanitized result:
  # `Music.safe_name/1` substitutes "track" for anything that reduces to
  # nothing, so a check on its output could never fire and "   " would quietly
  # become a sound called "track". Same reasoning as `StudioMix.safe_mix_name/1`.
  def renamed_to(name, stem) do
    if String.match?(stem, ~r/[\p{L}\p{N}]/u) do
      ext = Path.extname(name)

      clean =
        stem
        |> String.trim()
        |> BusterClaw.AudioName.safe_name()
        |> Path.rootname()
        |> String.trim()

      {:ok, clean <> ext}
    else
      {:error, :invalid_name}
    end
  end

  defp renamed(name, stem), do: renamed_to(name, stem)

  # Collisions refuse rather than auto-suffix: a rename is the user naming a
  # thing, and quietly handing back `bongos-2.wav` is not what they asked for.
  defp refuse_taken(new_name) do
    if new_name in list(), do: {:error, :name_taken}, else: :ok
  end

  defp repoint_map_value(old, new) do
    sound_map()
    |> Map.new(fn {key, value} -> {key, if(value == old, do: new, else: value)} end)
    |> persist_map()
  end

  @doc "Remove a sound file and any map entries routing to it."
  def delete(name) when is_binary(name) do
    case path_for(name) do
      nil ->
        {:error, :not_found}

      path ->
        with :ok <- File.rm(path) do
          prune_map_value(name)
          :ok
        end
    end
  end

  # ---------------------------------------------------------------------------
  # Per-event routing
  # ---------------------------------------------------------------------------

  @doc """
  The event→sound map (`%{"voicemail" => "wilhelm.wav", ...}`). Entries whose
  sound file no longer exists are dropped on read.
  """
  def sound_map do
    # A routing value may be a workspace sound, a bundled default (routing
    # "confirm" to the built-in "boot.wav" is legitimate), or the "silent"
    # sentinel (Phase 2): the explicit request for nothing, which the
    # resolution walk treats as a definitive stop rather than an inherit.
    valid = MapSet.new(list() ++ bundled_list() ++ [@silent])

    Settings.get(@map_key)
    |> decode_map()
    |> Map.filter(fn {key, value} -> key in @route_keys and value in valid end)
  end

  @doc "The routing value that means \"nothing, on purpose\"."
  def silent, do: @silent

  @doc """
  Route `key` (a source, kind, or `"default"`) to a library sound. `nil` or
  `""` clears the entry so the key inherits again.
  """
  def assign(key, name) when key in @route_keys do
    cond do
      name in [nil, ""] ->
        persist_map(Map.delete(sound_map(), key))

      name == @silent or name in list() or name in bundled_list() ->
        persist_map(Map.put(sound_map(), key, name))

      true ->
        {:error, :unknown_sound}
    end
  end

  def assign(_key, _name), do: {:error, :unknown_key}

  @doc """
  The sound name to play for a fired notification. Workspace layers first
  (routing map: source → kind → default; then the legacy `notify.<ext>` /
  first-file fallback), and the bundled synthesized set is the floor — so with
  a completely empty workspace library, a timer still rings with `timer.wav`.
  Returns `nil` only when a key has no bundled default either.
  """
  def for_notification(%{source: source, kind: kind}) do
    map = sound_map()

    # "silent" anywhere in the routed walk is a definitive answer, not an
    # inherit: routing a SOURCE to silent must not fall through to its kind's
    # sound, or "mute voicemails" would still ring on the timer chime.
    case map[source] || map[kind] || map["default"] do
      @silent -> nil
      nil -> default_name() || bundled_default(source) || bundled_default(kind)
      name -> name
    end
  end

  @doc "The sound name a routing key currently resolves to, walking inheritance."
  def resolved(key) when key in @route_keys do
    map = sound_map()

    routed =
      cond do
        map[key] -> map[key]
        key != "default" -> map["default"]
        true -> nil
      end

    case routed do
      @silent -> nil
      nil -> default_name() || bundled_default(key)
      name -> name
    end
  end

  # The bundled name for a routing key (`"timer"` → `"timer.wav"`), if the
  # generated set has one. Membership-checked, not assumed: a key without a
  # bundled file (only "default" today) falls through to nil rather than
  # minting a name that 404s.
  defp bundled_default(key) when is_binary(key) do
    name = key <> ".wav"
    if name in bundled_list(), do: name
  end

  defp bundled_default(_key), do: nil

  defp default_name do
    case path() do
      nil -> nil
      resolved -> Path.basename(resolved)
    end
  end

  # ---------------------------------------------------------------------------
  # Legacy single-chime resolution (the routing floor)
  # ---------------------------------------------------------------------------

  @doc """
  Absolute path to the fallback chime, or `nil` when none is present. Prefers a
  file explicitly named `notify.<ext>`; otherwise the first audio file in the
  folder.
  """
  def path do
    named_notify() || first_audio()
  end

  @doc "True when at least one chime is available to play."
  def available?, do: path() != nil

  @doc "The audio content-type for a resolved sound path."
  def content_type(sound_path) do
    Map.get(@content_types, sound_path |> Path.extname() |> String.downcase(), "audio/mpeg")
  end

  @doc """
  Create the `sounds/` folder and a README explaining how to wire a chime, so the
  feature is discoverable. Best-effort — never raises. No audio is bundled; the
  chime is operator-provided.
  """
  def ensure do
    File.mkdir_p(dir())
    readme = Path.join(dir(), "README.md")
    unless File.exists?(readme), do: File.write(readme, readme_body())
    :ok
  rescue
    error ->
      Logger.warning("Notifications.Sound.ensure failed: #{Exception.message(error)}")
      :ok
  end

  defp named_notify do
    Enum.find_value(@exts, fn ext ->
      candidate = Path.join(dir(), @preferred <> ext)
      if File.regular?(candidate), do: candidate
    end)
  end

  defp first_audio do
    case File.ls(dir()) do
      {:ok, entries} ->
        entries
        |> Enum.sort()
        |> Enum.map(&Path.join(dir(), &1))
        |> Enum.find(fn candidate ->
          File.regular?(candidate) and String.downcase(Path.extname(candidate)) in @exts
        end)

      _ ->
        nil
    end
  end

  defp decode_map(nil), do: %{}

  defp decode_map(json) when is_binary(json) do
    case Jason.decode(json) do
      {:ok, %{} = map} -> Map.filter(map, fn {k, v} -> is_binary(k) and is_binary(v) end)
      _ -> %{}
    end
  end

  defp persist_map(map) when map == %{} do
    Settings.delete(@map_key)
    :ok
  end

  defp persist_map(map) do
    case Settings.put(@map_key, Jason.encode!(map)) do
      {:ok, _} -> :ok
      {:error, _} = error -> error
    end
  end

  defp prune_map_value(name) do
    pruned = Map.reject(sound_map(), fn {_key, value} -> value == name end)
    persist_map(pruned)
  end

  defp readme_body do
    """
    # Notification sounds

    Audio files here are the notification sound library, managed from
    Settings → Notify — pick which sound plays for each kind of notification,
    preview them, and add more.

    - Accepted: `.mp3`, `.wav`, `.ogg`, `.m4a`, `.aac`.
    - With no routing configured, `notify.<ext>` (else the first audio file
      alphabetically) plays for everything.
    - No file here? Notifications still show their modal — just silently.
    """
  end
end
